VIA_ENABLE=yes

MCU = RP2040
BOOTLOADER = rp2040

SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE=yes
OLED_ENABLE = no
EXTRAKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes

BACKLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
BOOTMAGIC_ENABLE = no
LTO_ENABLE = yes


